name: Publish jars

on:
  push:
      tags:
        - '*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 20.0.1
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Set version
        run: mvn versions:set -DnewVersion=${{ github.ref_name }}-KC${{ matrix.version }}

      - name: Build
        run: |
            mvn -Dkeycloak.version=${{ matrix.version }} \
                -B package --file pom.xml

      - name: "Create release"
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          prerelease: false
          name: v${{ github.ref_name }}
          commit: ${{ github.ref_name }}
          generateReleaseNotes: true
          artifacts: target/keycloak-cef-logger*