name: Publish jars

on:
  push:
      tags:
        - '*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 20.0.1
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: |
            mvn -Dproject.version=${{ github.ref_name }}-KC${{ matrix.version }} \
                -Dkeycloak.version=${{ matrix.version }} \
                -B package --file pom.xml

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/keycloak-cef-logger*
          name: Keycloak CEF Logger v${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}