name: Publish package

on:
  release:
    types:
        - released

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 20.0.1  
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set version
        run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}-KC${{ matrix.version }}

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
